@hostName=http://127.0.0.1:8000
### Test the /ingest endpoint
# @name ingest
POST {{hostName}}/ingest
Content-Type: application/json

{
  "content": "This is a test document.",
  "metadata": {
    "author": "John Doe",
    "category": "test"
  }
}

### Test the /retrieve endpoint
# name of the document to retrieve
# @name retrieve
GET {{hostName}}/retrieve
Content-Type: application/json

{
  "query": "test document"
}

### Test the /delete endpoint
# @name delete
DELETE {{hostName}}/delete/1